# Generated by Django 4.2.16 on 2024-09-05 17:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ToDo', '0002_postheader_delete_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostHeader',
            new_name='Post',
        ),
    ]
